# ------------------------------------------------------------------------------
# ----------------------------------- Basic ------------------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'vim-denops/denops.vim'  # deno operators
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'denops.vim'
'''

# ------------------------------------------------------------------------------
# ---------------------------- Neovim compatibility ----------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'roxma/nvim-yarp'
if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '!has("nvim")'

# ------------------------------------------------------------------------------
# ------------------------------ Extra Functions -------------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'embear/vim-localvimrc'                 # Local vimrc
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-localvimrc.vim'
'''

[[plugins]]
repo = 'scrooloose/nerdtree'                   # Filer
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'nerdtree.vim'
'''

[[plugins]]
repo = 'mbbill/undotree'                       # undo可視化
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'undotree.vim'
'''

[[plugins]]
repo = 'simeji/winresizer'                     # ウィンドウリサイズ
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'winresizer.vim'
'''

[[plugins]]
repo = 'vim-scripts/YankRing.vim'              # ヤンク履歴
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'yankring.vim'
'''

[[plugins]]
repo = 'thinca/vim-ref'                        # 英語オンライン辞書
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-ref.vim'
'''

[[plugins]]
repo = 'skywind3000/asyncrun.vim'              # 非同期実行
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'asyncrun.vim'
'''

# ------------------------------------------------------------------------------
# --------------------------------- Completion ---------------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'neovim/nvim-lspconfig'  # LSP configuration
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'nvim-lspconfig.vim'
'''

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'  # LSP installer (:LSPInstallInfo)
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'nvim-lsp-installer.vim'
'''

[[plugins]]
repo = 'Shougo/ddc-matcher_head'  # ddc plugin

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'   # ddc plugin

[[plugins]]
repo = 'LumaKernel/ddc-file'      # ddc plugin

[[plugins]]
repo = 'Shougo/ddc-around'        # ddc plugin

[[plugins]]
repo = 'matsui54/ddc-dictionary'  # ddc plugin

[[plugins]]
repo = 'LumaKernel/ddc-tabnine'   # ddc plugin

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'      # ddc plugin

[[plugins]]
repo = 'takiyu/my-vim-snippets'   # snippet for ddc plugin

[[plugins]]
repo = 'Shougo/neosnippet'        # ddc plugin
depends = ['my-vim-snippets']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'neosnippet.vim'
'''

[[plugins]]
repo = 'Shougo/ddc.vim'           # ddc body
depends = ['denops.vim', 'ddc-around', 'ddc-matcher_head', 'ddc-sorter_rank',
           'ddc-nvim-lsp', 'ddc-file', 'neosnippet']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'ddc.vim'
'''

[[plugins]]
repo = 'matsui54/denops-signature_help'     # lsp enhancer
depends = ['denops.vim', 'ddc.vim']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'denops-signature_help.vim'
'''

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'  # lsp enhancer
depends = ['denops.vim', 'ddc.vim']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'denops-popup-preview.vim'
'''

# ------------------------------------------------------------------------------
# ------------------------------------ Git -------------------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'airblade/vim-gitgutter'                # Git差分ガイド
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-gitgutter.vim'
'''

[[plugins]]
repo = 'tpope/vim-fugitive'                    # Git補助

[[plugins]]
repo = 'Shougo/vimproc.vim'                    # agitが依存
build = 'make'

[[plugins]]
repo = 'cohama/agit.vim'                       # Git Graph
depends = ['vimproc.vim']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'agit.vim'
'''

# ------------------------------------------------------------------------------
# ----------------------------- Indent Assistance ------------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'tpope/vim-sleuth'                      # インデント自動検出

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'       # インデント明示化
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-indent-guides.vim'
'''

# ------------------------------------------------------------------------------
# ----------------------------- Comment Assistance -----------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'tyru/caw.vim'                          # コメントアウト補助
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'caw.vim'
'''

[[plugins]]
repo = 'takiyu/split_commenter.nvim'           # 分割コメント補助
depends = ['caw.vim']

# ------------------------------------------------------------------------------
# ----------------------------- Cursor Assistance ------------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'rhysd/clever-f.vim'                    # カーソル移動 (f)
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'clever-f.vim'
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'             # カーソル移動 (s)
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-easymotion.vim'
'''

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'         # Smooth scroll
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'comfortable-motion.vim'
'''

# ------------------------------------------------------------------------------
# --------------------------------- Appearance ---------------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'takiyu/tango-lx'                       # カラースキーム

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'       # 行末スペース可視化

[[plugins]]
repo = 'josa42/nvim-lightline-lsp'             # ステータスライン for lsp
depends = ['nvim-lspconfig']

[[plugins]]
repo = 'itchyny/lightline.vim'                 # ステータスライン
depends = ['vim-fugitive', 'nvim-lightline-lsp']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'lightline.vim'
'''

[[plugins]]
repo = 'vimtaku/hl_matchit.vim'                # 括弧+αをハイライト
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'hl_matchit.vim'
'''

[[plugins]]
repo = 't9md/vim-quickhl'                      # ハイライト
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-quickhl.vim'
'''

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
