[[plugins]]
repo = 'Shougo/deoplete.nvim'                  # 補完
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'deoplete.vim'
'''

[[plugins]]
repo = 'takiyu/deoplete-tabnine'                # All-language autocompleter
rev = 'binary'
depends = ['deoplete.nvim']
# hook_post_update = '''
#     if dein#util#_is_windows()
#         let g:dein#plugin.build = 'powershell -executionpolicy bypass -File install.ps1'  " For windows
#     else
#         let g:dein#plugin.build = 'bash ./install.sh'  " For linux
#     endif
# '''

[[plugins]]
repo = 'roxma/nvim-yarp'                       # neovim compatibility
if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'              # neovim compatibility
if = '!has("nvim")'

[[plugins]]
repo = 'Shougo/neosnippet'                     # Snippet
depends = ['deoplete.nvim']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'neosnippet.vim'
'''

[[plugins]]
repo = 'takiyu/my-vim-snippets'                # Snippet
depends = ['neosnippet.vim']

[[plugins]]
repo = 'takiyu/tango-lx'                       # カラースキーム

[[plugins]]
repo = 'tyru/caw.vim'                          # コメントアウト補助
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'caw.vim'
'''

[[plugins]]
repo = 'scrooloose/nerdtree'                   # Filer
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'nerdtree.vim'
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'                    # カーソル移動 (f)
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'clever-f.vim'
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'             # カーソル移動 (s)
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-easymotion.vim'
'''

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'         # Smooth scroll
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'comfortable-motion.vim'
'''

[[plugins]]
repo = 'itchyny/lightline.vim'                 # ステータスライン
depends = ['vim-fugitive', 'lightline-languageclient.vim']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'lightline.vim'
'''

[[plugins]]
repo = 'takiyu/lightline-languageclient.vim'   # lightline with LanguageClient

[[plugins]]
repo = 'simeji/winresizer'                     # ウィンドウリサイズ
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'winresizer.vim'
'''

[[plugins]]
repo = 't9md/vim-quickhl'                      # ハイライト
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-quickhl.vim'
'''

[[plugins]]
repo = 'vimtaku/hl_matchit.vim'                # 括弧+αをハイライト
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'hl_matchit.vim'
'''

[[plugins]]
repo = 'vim-scripts/YankRing.vim'              # ヤンク履歴
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'yankring.vim'
'''

[[plugins]]
repo = 'mbbill/undotree'                       # undo可視化
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'undotree.vim'
'''

[[plugins]]
repo = 'tpope/vim-sleuth'                      # インデント自動検出

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'       # インデント明示化
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-indent-guides.vim'
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'       # 行末スペース可視化

[[plugins]]
repo = 'airblade/vim-gitgutter'                # Git差分ガイド
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-gitgutter.vim'
'''

[[plugins]]
repo = 'tpope/vim-fugitive'                    # Git補助

[[plugins]]
repo = 'Shougo/vimproc.vim'                    # agitが依存
build = 'make'

[[plugins]]
repo = 'cohama/agit.vim'                       # Git Graph
depends = ['vimproc.vim']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'agit.vim'
'''

[[plugins]]
repo = 'skywind3000/asyncrun.vim'              # 非同期実行
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'asyncrun.vim'
'''

[[plugins]]
repo = 'embear/vim-localvimrc'                 # Local vimrc
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-localvimrc.vim'
'''

[[plugins]]
repo = 'ujihisa/neco-look'                     # 英単語補完

[[plugins]]
repo = 'thinca/vim-ref'                        # 英語オンライン辞書
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-ref.vim'
'''
