# ------------------------------------------------------------------------------
# --------------------------------- Completion ---------------------------------
# ------------------------------------------------------------------------------
# Note: Loading config when plugins are loaded, to apply autocmd for filetype.
[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
on_ft = ['c', 'cpp', 'python', 'java', 'glsl']
depends = ['deoplete.nvim']
build = 'bash install.sh'
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'languageclient.vim'
'''

[[plugins]]
repo = 'takiyu/fast_clang_format.nvim'
on_ft = ['c', 'cpp', 'java', 'javascript']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'fast_clang_format.vim'
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-go.vim'
'''

[[plugins]]
repo = 'LaTeX-Box-Team/LaTeX-Box'
on_ft = ['tex', 'plaintex']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'latex-box.vim'
'''

# ------------------------------------------------------------------------------
# ---------------------------------- Syntaxes ----------------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = ['cpp']

[[plugins]]
repo = 'tikhomirov/vim-glsl'
on_ft = ['glsl']

# [[plugins]]
# repo = 'hallison/vim-markdown'
# on_ft = ['markdown']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-json.vim'
'''

[[plugins]]
repo = 'gutenye/json5.vim'
on_ft = ['json5']

[[plugins]]
repo = 'neoclide/jsonc.vim'
on_ft = ['jsonc']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'vim-scripts/verilog.vim'
on_ft = ['verilog']

# ------------------------------------------------------------------------------
# ---------------------------- Document Generation -----------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'vim-scripts/DoxygenToolkit.vim'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'heavenshell/vim-pydocstring'
on_ft = ['python']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-pydocstring.vim'
'''

[[plugins]]
repo = 'LeafCage/vimhelpgenerator'
on_ft = ['vim']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vimhelpgenerator.vim'
'''

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
