# ------------------------------------------------------------------------------
# ---------------------------- Neovim compatibility ----------------------------
# ------------------------------------------------------------------------------
# [[plugins]]
# repo = 'roxma/nvim-yarp'           # (Vim only)
# if = '!has("nvim")'
#
# [[plugins]]
# repo = 'roxma/vim-hug-neovim-rpc'  # (Vim only)
# if = '!has("nvim")'

# ------------------------------------------------------------------------------
# ------------------------------ Extra Functions -------------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'pysan3/autosession.nvim'               # セッション管理
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'autosession.vim'
'''

[[plugins]]
repo = 'embear/vim-localvimrc'                 # Local vimrc
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-localvimrc.vim'
'''

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
[[plugins]]
repo = 'lambdalisue/fern.vim'                  # Filer
depends = ['nerdfont.vim', 'glyph-palette.vim', 'fern-renderer-nerdfont.vim']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'fern.vim'
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'         # Fuzzy Finder
depends = ['plenary.nvim']
[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
depends = ['telescope.nvim']
build = 'make'
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'telescope.vim'
'''

[[plugins]]
repo = 'mbbill/undotree'                       # undo可視化
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'undotree.vim'
'''

[[plugins]]
repo = 'simeji/winresizer'                     # ウィンドウリサイズ
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'winresizer.vim'
'''

[[plugins]]
repo = 'vim-scripts/YankRing.vim'              # ヤンク履歴
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'yankring.vim'
'''

[[plugins]]
repo = 'windwp/nvim-autopairs'                 # カッコ自動入力
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'nvim-autopairs.vim'
'''

[[plugins]]
repo = 'thinca/vim-ref'                        # 英語オンライン辞書
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-ref.vim'
'''

[[plugins]]
repo = 'skywind3000/asyncrun.vim'              # 非同期実行
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'asyncrun.vim'
'''

[[plugins]]
repo = 'akinsho/toggleterm.nvim'               # Terminal
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'toggleterm.vim'
'''

[[plugins]]
repo = 'dstein64/vim-startuptime'              # :StartupTime

# ------------------------------------------------------------------------------
# ----------------------------------- Syntax -----------------------------------
# ------------------------------------------------------------------------------
# [[plugins]]
# repo = 'nvim-treesitter/nvim-treesitter'  # 動的シンタックス
# hook_add = '''
#     execute 'source ' . g:dein_plugin_config_dir . 'nvim-treesitter.vim'
# '''

# ------------------------------------------------------------------------------
# ------------------------------------ LSP -------------------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'neovim/nvim-lspconfig'                 # LSP
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'nvim-lspconfig.vim'
'''

[[plugins]]
repo = 'williamboman/mason.nvim'               # LSP installer
[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'mason.vim'
'''

[[plugins]]
repo = 'ray-x/lsp_signature.nvim'              # Signature
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'lsp_signature.vim'
'''

[[plugins]]
repo = 'onsails/lspkind.nvim'                  # LSP icon

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'                  # Completion
[[plugins]]
repo = 'hrsh7th/vim-vsnip'
[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
[[plugins]]
repo = 'hrsh7th/cmp-buffer'
[[plugins]]
repo = 'hrsh7th/cmp-path'
[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
[[plugins]]
repo = 'octaltree/cmp-look'
[[plugins]]
repo = 'tzachar/cmp-tabnine'
build = './install.sh'
[[plugins]]
repo = 'hrsh7th/cmp-emoji'
[[plugins]]
repo = 'hrsh7th/cmp-calc'
[[plugins]]
repo = 'hrsh7th/nvim-cmp'
depends = ['cmp-nvim-lsp', 'vim-vsnip', 'cmp-vsnip', 'cmp-buffer', 'cmp-path',
           'cmp-cmdline', 'cmp-look', 'cmp-tabnine', 'cmp-emoji', 'cmp-calc',
           'lspkind.nvim']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'nvim-cmp.vim'
'''

# ------------------------------------------------------------------------------
# ------------------------------------ Git -------------------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'airblade/vim-gitgutter'                # Git差分ガイド
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-gitgutter.vim'
'''

[[plugins]]
repo = 'tpope/vim-fugitive'                    # Git補助

# ------------------------------------------------------------------------------
# ----------------------------- Indent Assistance ------------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'tpope/vim-sleuth'                      # インデント自動検出

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'       # インデント明示化
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-indent-guides.vim'
'''

# ------------------------------------------------------------------------------
# ----------------------------- Comment Assistance -----------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'tyru/caw.vim'                          # コメントアウト補助
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'caw.vim'
'''

[[plugins]]
repo = 'takiyu/split_commenter.nvim'           # 分割コメント補助
depends = ['caw.vim']

# ------------------------------------------------------------------------------
# ----------------------------- Cursor Assistance ------------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'rhysd/clever-f.vim'                    # カーソル移動 (f)
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'clever-f.vim'
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'             # カーソル移動 (s)
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-easymotion.vim'
'''

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'         # Smooth scroll
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'comfortable-motion.vim'
'''

# ------------------------------------------------------------------------------
# --------------------------------- Appearance ---------------------------------
# ------------------------------------------------------------------------------
[[plugins]]
repo = 'takiyu/tango-lx'                  # カラースキーム

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'  # 行末スペース可視化

[[plugins]]
repo = 'josa42/nvim-lightline-lsp'        # Status line for lsp

[[plugins]]
repo = 'itchyny/lightline.vim'            # Status line
depends = ['vim-fugitive', 'nvim-lightline-lsp']
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'lightline.vim'
'''

[[plugins]]
repo = 'vimtaku/hl_matchit.vim'           # 括弧+αをハイライト
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'hl_matchit.vim'
'''

[[plugins]]
repo = 't9md/vim-quickhl'                 # ハイライト
hook_add = '''
    execute 'source ' . g:dein_plugin_config_dir . 'vim-quickhl.vim'
'''

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
